config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      post "/matching", to: "users#matching"
      get '/location', to: "users#set_user_location"
      post '/location/set', to: "users#post_locate"
    end
  end

  # routes for user registration
  get 'registration/welcome', to: 'registration#welcome_page'
  get 'registration/cuisines', to: 'registration#cuisines_show'
  post 'registration/cuisines/edit', to: 'registration#cuisines_edit'
  get 'registration/interests', to: 'registration#interests_show'
  post 'registration/interests/edit', to: 'registration#interests_edit'
  get 'registration/bio', to: 'registration#bio_show'
  post 'registration/bio/edit', to: 'registration#bio_edit'
  get 'registration/completed', to: 'registration#registration_completed'


  resources :recipes, only: [:index, :show, :new, :create]

  post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room
  get 'chat_rooms', to: 'chat_rooms#index'

  mount ActionCable.server => "/cable"

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :match
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  layout "registration", only: [:show]
  require 'open-uri'
  require 'nokogiri'
  def show
    @chat_room = ChatRoom.includes(messages: :user).find(params[:id])
    # Recipe.destroy_all
    scrapeing_recipe
    @recipes = policy_scope(Recipe)
  end

  def index
    @my_chats = []
    ChatRoom.all.each do |chat|
      if chat.match.user1 == current_user || chat.match.user2 == current_user
        @my_chats << chat
      end
    end
  end

  private
  def scrapeing_recipe
    @match = @chat_room.match
    match_array = @chat_room.match.user1.cuisine_list & @chat_room.match.user2.cuisine_list
    if match_array.empty?
      cuisine = "indonesian"
    else
      cuisine = match_array.first.downcase
    end
    url = "https://food52.com/recipes/#{cuisine}"
    base_url = "https://food52.com"
    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)
    html_doc.search('.collectable-tile .photo-block a').take(1).each do |element|
      @url = base_url + element.attribute('href')
      @image_url = element.first_element_child.attribute('src')
      @name = element.attribute('title')
      @recipe = Recipe.create!(match_id: @match.id, name: @name, url: @url, image_url: @image_url)
    end
  end

end

app/views/chat_rooms/index.html.erb
<div class="phonepage-chat-index">
  <div class="header-matches">
    <h1>Messages</h1>
  </div>
  <div class="match-chats">
    <% if @my_chats.size > 0 %>
      <% @my_chats.each do |chat| %>
        <div class="match-card">
          <div class= "user-avatar">
            <% if chat.match.user1 != current_user %>
              <%= image_tag chat.match.user1.facebook_picture_url, class:"avatar-chat" %>
            <% else %>
              <%= image_tag chat.match.user2.facebook_picture_url ,class:"avatar-chat" %>
            <% end %>
          </div>
          <div class="match-message-card">
            <div class="match-message-name">
              <% if chat.match.user1 != current_user %>
                <%= link_to chat.match.user1.first_name, chat_room_path(chat) %>
              <% else %>
                <%= link_to chat.match.user2.first_name, chat_room_path(chat) %>
              <% end %>
            </div>
            <div class="match-message-content">
              <%= chat.messages.empty? ? "No messages yet!" : chat.messages.last.content %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p> You have no matches yet</p>
    <% end %>
  </div>
</div>
<h1 class="gold-text">The Blog Market</h1>

app/views/chat_rooms/show.html.erb
<div class="phone-page-message">
  <%= link_to ' ← Back', chat_rooms_path, class: "btn-chat" %>
  <!--  -->
  <div class="container chatting">
    <div class="row-chat">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="chat-header" id= "target-for-recipe">
          <% if @chat_room.match.user1 != current_user %>
            <h4> <%= @chat_room.match.user1.first_name %></h4>
          <% else %>
            <h4> <%= @chat_room.match.user2.first_name %></h4>
          <% end %>
        </div>
        <div id="recipe-slider">
          <h4>  ↓ Recipe</h4>
        </div>
        <div id="recipe-content" class="recipe-dropdown-content recipe-bar-block recipe-border">
          <div class="recipe-image">
            <%= image_tag(@recipe.image_url) %>
          </div>
          <div class="dark-overlay"></div>
          <div class="recipe-name">
            <p> <%= link_to @recipe.name, @recipe.url %></p>
          </div>
        </div>
        <div class="messages">
          <% @chat_room.messages.each do |message| %>
            <%= render "messages/message", message: message, user_is_messages_author: message.user == current_user %>
          <% end %>
        </div>
        <div id="create-message">
          <%= simple_form_for [ @chat_room, Message.new ], remote: true, html: {autocomplete: "off" } do |f| %>
            <%= f.input :content, label: false %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% content_for :after_js do %>
    <script>
      scrollLastMessageIntoView();
      App['chat_room_<%= @chat_room.id %>'] = App.cable.subscriptions.create({ channel: 'ChatRoomsChannel', chat_room_id: <%= @chat_room.id %> }, {
        received: (data) => {
          if (data.current_user_id !== <%= current_user.id %>) {
            const messagesContainer = document.querySelector('.messages');
            messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
            scrollLastMessageIntoView();
          }
        }
      })
    </script>
  <% end %>
</div>