config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      post "/matching", to: "users#matching"
      get '/location', to: "users#set_user_location"
      post '/location/set', to: "users#post_locate"
    end
  end

  # routes for user registration
  get 'registration/welcome', to: 'registration#welcome_page'
  get 'registration/cuisines', to: 'registration#cuisines_show'
  post 'registration/cuisines/edit', to: 'registration#cuisines_edit'
  get 'registration/interests', to: 'registration#interests_show'
  post 'registration/interests/edit', to: 'registration#interests_edit'
  get 'registration/bio', to: 'registration#bio_show'
  post 'registration/bio/edit', to: 'registration#bio_edit'
  get 'registration/completed', to: 'registration#registration_completed'


  resources :recipes, only: [:index, :show, :new, :create]

  post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room
  get 'chat_rooms', to: 'chat_rooms#index'

  mount ActionCable.server => "/cable"

end

app/models/user.rb
class User < ApplicationRecord
  CUISINES = ["Israeli", "Japanese", "Italian", "Thai", "Chinese", "Mexican", "Greek", "Chinese", "French", "Korean", "Indian", "Spanish"].freeze
  INTERESTS = ["Swim", "Cook", "Bake", "Read", "Travel", "Run", "Draw", "Play piano", "Write", "Meet new people"].freeze
  RESTRICTIONS = ["Gluten-Free", "Lactose-Free", "Vegetarian", "Kosher", "Vegan"].freeze
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  acts_as_votable
  acts_as_voter
  acts_as_taggable
  acts_as_taggable_on :cuisines, :interests, :restrictions

  # geocoder
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  def self.all_except(user)
    where.not(id: user)
  end

  def matched?(user2)
    self.liked? user2
  end

  def random_user
    @users = User.all_except(current_user)
  end
  # this is for the redirection of new user or already registered user
  def full_profile?
    !self.cuisine_list.empty?
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
    # @current_user = current_user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user

    redirect_to user_path(@user)
  end

  def matching
    @user = User.find(params[:id])
    authorize @user
    current_user.likes @user
    if @user.matched?(current_user)
      match = Match.create!(user1_id: current_user.id, user2_id: @user.id)
      ChatRoom.create!(match: match)
      redirect_to user_path(User.all_except(current_user).sample, match: "matches", name: @user.first_name)
      # redirect_to user_path(current_user.nearbys.sample(1)) commented out for demo
    else
      redirect_to user_path(User.all_except(current_user).sample)
      # redirect_to user_path(current_user.nearbys.sample(1)) commented out for demo
    end
  end

  def set_user_location
    @user = current_user
    authorize @user
  end

  def post_locate
    @user = current_user
    authorize @user
    latitude = params[:search][:query].split(',').first.to_f
    longitude = params[:search][:query].split(',').second.to_f
    @user.update_columns(
      latitude: latitude,
      longitude: longitude
    )
    @user.save
    redirect_to user_path(User.all_except(current_user).sample)
    # redirect_to user_path(current_user.nearbys.sample.id) commented out for demo
  end
end

app/views/users/edit.html.erb
<div class="phonepage">
  <div class="swipecard-edit">
    <div class="user-img-swipe">
      <% if current_user.facebook_picture_url.nil? %>
        <% current_user.facebook_picture_url = "https://articles-images.sftcdn.net/wp-content/uploads/sites/3/2016/01/wallpaper-for-facebook-profile-photo.jpg"%>
      <% end  %>
      <%= image_tag (current_user.facebook_picture_url) %>
    </div>
    <div class="info-edit">
      <div class="name-header">
        <% if current_user.full_name.length <= 10 %>
          <h1><%= current_user.full_name %></h1>
        <% else %>
          <h3><%= current_user.full_name %></h3>
        <% end %>
      </div>
      <div class="row_cuisines">
        <div class="chef">
          <%= image_tag("chef.png") %>
        </div>
        <div class="cuisines-list tags">
          <% current_user.cuisine_list.each do |cuisine| %>
            <span class="tag"><%= cuisine %></span>
          <% end %>
        </div>
      </div>
      <div class="row_interests">
        <div class="smile-happy">
          <%= image_tag("happiness.png") %>
        </div>
        <div class="interest-list tags">
          <p><% current_user.interest_list.each do |interest| %>
              <span class="tag"><%= interest %></span>
            <% end %></p>
        </div>
      </div>
      <div class="row_restrictions">
        <div class="gluten-free">
          <%= image_tag("gluten-free.png") %>
        </div>
        <div class="restriction-list tags">
          <% current_user.restriction_list.each do |restriciton| %>
            <span class="tag"><%= restriciton %></span>
          <% end %>
        </div>
      </div>
      <div class="edit-bio custom-scrollbar">
        <h5>Your biography:</h5>
        <p><%= current_user.bio %></p>
      </div>
    </div>
  </div>
  <div class="sign-out">
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
    <% end %>
  </div>
</div>
<!--  -->

app/views/users/matching.js.erb
<% if @message %>
  alert(<%=j @message %>);
<% end %>

app/views/users/no_users_around.html.erb
<h1>No one is around</h1>

app/views/users/set_user_location.html.erb
<h1>Get started</h1>
<%= simple_form_for :search, url:  location_set_user_path, method: :post do |f| %>
  <%= f.input :query, as: :hidden %>
  <%= f.submit 'Authorize my location'%>
<% end %>

app/views/users/show.html.erb
<div class="phonepage">
  <div class="swipecard">
    <script src="sweetalert2.all.min.js"></script>
    <div class="user-img-swipe">
      <%= image_tag (@user.facebook_picture_url) %>
    </div>
    <div class="info">
      <div class="name-header">
        <% if @user.full_name.length <= 10 %>
          <h1><%= @user.full_name %></h1>
        <% else %>
          <h3><%= @user.full_name %></h3>
        <% end %>
      </div>
      <div class="row_cuisines">
        <div class="chef">
          <%= image_tag("chef.png") %>
        </div>
        <div class="cuisines-list tags">
          <% @user.cuisine_list.each do |cuisine| %>
            <span class="tag"><%= cuisine %></span>
          <% end %>
        </div>
      </div>
      <div class="row_interests">
        <div class="smile-happy">
          <%= image_tag("happiness.png") %>
        </div>
        <div class="interest-list tags">
          <p><% @user.interest_list.each do |interest| %>
              <span class="tag"><%= interest.capitalize %></span>
            <% end %></p>
        </div>
      </div>
    </div>
  </div>
  <div id="target-hide-icon-navbar"></div>
  <div class="like">
    <%= link_to matching_user_path(id: @user.id), method: :post, class: "navbar-wagon-brand" do %>
      <%= image_tag "heart.png" %>
    <% end %>
  </div>
  <div class="dislike">
    <%= link_to matching_user_path(id: @user.id), method: :post, class: "navbar-wagon-brand" do %>
      <%= image_tag "cancel.png" %>
    <% end %>
  </div>
</div>
<% if params["match"] == "matches" %>
  <div id="sweet-alert-target" value= <%= params["name"] %>></div>
<% end %>