config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit, :update, :show] do
    member do
      post "/matching", to: "users#matching"
      get '/location', to: "users#set_user_location"
      post '/location/set', to: "users#post_locate"
    end
  end

  # routes for user registration
  get 'registration/welcome', to: 'registration#welcome_page'
  get 'registration/cuisines', to: 'registration#cuisines_show'
  post 'registration/cuisines/edit', to: 'registration#cuisines_edit'
  get 'registration/interests', to: 'registration#interests_show'
  post 'registration/interests/edit', to: 'registration#interests_edit'
  get 'registration/bio', to: 'registration#bio_show'
  post 'registration/bio/edit', to: 'registration#bio_edit'
  get 'registration/completed', to: 'registration#registration_completed'


  resources :recipes, only: [:index, :show, :new, :create]

  post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room
  get 'chat_rooms', to: 'chat_rooms#index'

  mount ActionCable.server => "/cable"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" id="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" id= "alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <% if user_signed_in? %>
    <div class="profile-icon">
      <%= link_to edit_user_path(current_user), class: "navbar-wagon-brand" do %>
        <%= image_tag "user-grey.png", height: 50 %>
      <% end %>
    </div>
    <div class="matching-icon">
      <!-- current_user.nearbys.sample(1)  commented out for demo-->
      <%= link_to user_path(User.all_except(current_user).sample), class: "navbar-wagon-brand" do %>
        <%= image_tag "fork.png", height: 50 %>
      <% end %>
    </div>
    <div class="paper-plane-icon">
      <%= link_to chat_rooms_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "chat.png", height: 50 %>
      <% end %>
    </div>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>
</div>